// Now in JS! This truly is a frontend moment.
var splashes = [
    'It\'s Archaic!',
    'Think. Build. Create.',
    'MORBLOX never existed.',
    'You make the game.',
    'Memories under the arch.',
    'Watch out for Archviles!',
    'We\'re still Morbin\'',
    'Why yes I play ARCHBLOX, how could you tell?',
    'Do not sell us expensive helicopters',
    'Get better at archery with ARCHBLOX!!!',
    'my bitch got me a walle hat from disney land',
    'We are powering laziness',
    'If you can\'t beat em, join em',
    'We will, we will rock you',
    'I\'m a goofy goober',
    'I LOVE BEING PURPLE',
    'The slogan always changes!',
    'Crosswoods is a great game!',
    'The oldest anarchy server in minecraft.',
    'Good morning U.S.A!',
    'I\'ve got a feeling that it\'s gonna be a wonderful day',
    'The sun in the sky has a smile on his face',
    'And he\'s shining a salute to the American race',
    'OOOH ARCHBLOX\'S OH YEAH',
    'you know what they say all toasters toast toast',
    'omg old roblox!!',
    'Thomas was here!',
    'C# moment!',
    'Laravel moment!',
    '?????????????',
    'If you play, you play.',
    'You die, you respawn.',
    'You game... the build?',
    '#announcements is an inside job',
    'Buy our stocks or we\'ll buy your soul!',
    'The physical equivalent to HALO, apparently',
    ':epic:',
    'Arrrrrr! I\'m a pirate!',
    'Now with 1337 viruses!',
    'Are these slogans funny?',
    'my dad left me',
    'Never going to give you up',
    'Never going to let you down.',
    'Never going to run around and desert you.',
    'We\'re all goofy goobers.',
    'you play like an noob dont add me',
    'Half-Life 3... confirmed?',
    'sponge boy me bob..',
    'yea mr krabs?',
    'promise me you\'ll never install archblox ooghghIMFUCKING DYING',
    'okay mr krabs',
    'conkley is EPIC',
    'skeuomorphism is awesome',
    'It\'s free!',
    'It\'s archtastic!',
    'The plural of horse is heese',
    'SUPER MARIO SUPER MARIO WORLD',
    'We\'re still dead!',
    'This shit is dead bro',
    'I\'m Glenn Quagmire.',
    'JESSE LOOK, IM SANS!',
    'I ain\'t reading allat :joy:',
    'i can\'t take it much longer',
    'wtf',
    'Obey the iPhone 5.',
    'This slogan has been sponsored by Buy-n-Large!',
    'Now with IP leaks!',
    'This slogan has been sponsored by RAID: SHADOW LEGENDS.',
    'This slogan has been sponsored by Super Mario 8.',
    'wawsdawsdwasdwasdwawds',
    'Hello Mario.',
    'Luigi is ALWAYS watching.',
    'HTML moment!',
    '(╯°□°)╯︵ ┻━┻',
    'Swift moment!',
    'Lua moment!',
    'Objective-C moment!',
    'JavaScript moment!',
    'PHP moment!',
    'CSS moment!',
    'the background-gradient in question:'
]

var splash = Math.floor(Math.random()*splashes.length);

document.addEventListener('DOMContentLoaded', function() {
    document.getElementById("morbin").innerHTML = splashes[splash];
});